--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TeamBixby/libCommandOverload
build-by-default: true
branches:
- master
projects:
  libCommandOverload:
    path: ""
    model: virion
    type: library
...
